p.42_1 readlineを使うには、tsconfigのtypesにnodeを指定する必要があった。 src/index.ts:1:33 - error TS2591: Cannot find name 'readline'. Do you need to install type definitions for node? Try changed 1 package, and audited 5 packages in 2s
found 0 vulnerabilities and then add 'node' to the types field in your tsconfig.